package:
  name: dedop
  version: "0.5.0"   #  {{ GIT_DESCRIBE_TAG }}

build:
  #string: 'rc0'
  number: 0  # {{ GIT_DESCRIBE_NUMBER }}
  # noarch_python: True
  # preserve_egg_dir: False
  osx_is_app: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - dedop = dedop.ui.cli:main

source:
  # git_rev: v0.5.0-rc0+1
  git_url: https://github.com/DeDop/dedop.git
  # The following does not work, i.e. typing "conda build recipe" will loop forever
  #path: ../

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pytest-cov

  run:
    - python
    - jupyter
    - ipywidgets
    - basemap
    - matplotlib
    - netcdf4
    - scipy
    - numpy

test:
  # Python imports
  imports:
    - dedop
    - dedop.ui
    - dedop.ui.analysis
    - dedop.ui.cli

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - dedop --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

app:
  entry: dedop
  icon: dedop-64.png
  own_environment: False
  summary:  "Delay Doppler Altimeter Tool"

about:
  home: https://github.com/DeDop/dedop
  license: GPL-3
  license_file: LICENSE
  summary: "DeDop is a User Configurable Tool for Processing Delay Doppler Altimeter Data."



# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
