package:
  name: dedop
  version: "0.5.0"

build:
  #string: 'rc0'
  number: 0
  # noarch_python: False
  # preserve_egg_dir: False
  osx_is_app: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - dedop = dedop.ui.cli:main

source:
  # git_rev: v0.5.0-rc0+1
  git_url: https://github.com/DeDop/dedop.git
  # Uncomment to skip the "git clone" step
  # path: ../../dedop

requirements:
  build:
    - python 3.5*
    - setuptools
    - pytest
    - pytest-cov

  run:
    - python 3.5*
    - numpy
    - scipy
    - netcdf4
    # dedop.ui.analysis only:
    - pyproj
    - matplotlib
    - bokeh
    - jupyter
    - ipywidgets
    - menuinst                    # [win]

test:
  # Python imports
  imports:
    - dedop
    - dedop.ui
    - dedop.ui.cli
    - dedop.ui.analysis

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - dedop --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

app:
  entry: dedop                                 # [not osx]
  entry: open ${PREFIX}/bin/dedop.command      # [osx]
  icon: dedop.png
  own_environment: False
  summary:  "Delay Doppler Altimeter Tool"

about:
  home: https://github.com/DeDop/dedop
  license: GPL-3
  license_file: LICENSE
  summary: "DeDop is a User Configurable Tool for Processing Delay Doppler Altimeter Data."



# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
