# Not released/deployed yet! Use PEP 440 versioning scheme
# ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
package:
  name: dedop
  version: "1.4.0.dev1"

build:
  number: 0
  # noarch_python: False
  # preserve_egg_dir: False
  # osx_is_app: False
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - dedop = dedop.cli.main:main

source:
  git_rev: python-36
  git_url: https://github.com/DeDop/dedop-core.git
  # Uncomment to skip the "git clone" step
  # path: ../../dedop

# versioning of the requirements follow the guideline here https://conda.io/docs/spec.html#build-version-spec
requirements:
  build:
    - python 3.6*
    - cate-util 1.1.0.dev1 py36_0
    - hdf4 ==4.2.12
    - netcdf4 ==1.2.4
    - numexpr ==2.6.4
    - numpy ==1.11.3
    - scipy ==1.0.0
    #
    # dedop.ui.analysis only:
    - bokeh ==0.12.13
    - ipywidgets ==7.1.1
    - jupyter ==1.0.0
    - matplotlib ==2.0.2
    - pyproj ==1.9.5.1
    #
    # build
    - setuptools
    - pytest
    - pytest-cov

  run:
    - python 3.6*
    - cate-util 1.1.0.dev1 py36_0
    - hdf4 ==4.2.12
    - netcdf4 ==1.2.4
    - numexpr ==2.6.4
    - numpy ==1.11.3
    - scipy ==1.0.0
    #
    # dedop.ui.analysis only:
    - bokeh ==0.12.13
    - ipywidgets ==6.0.1
    - jupyter ==1.0.0
    - matplotlib ==2.0.2
    - pyproj ==1.9.5.1

test:
  # Python imports
  imports:
    - dedop
    - dedop.ui
    - dedop.cli.main
    # for the moment this is disabled because it somehow failed in windows. A manual test has been performed
    # and it worked. More investigation needs to be done to understand why
    #- dedop.ui.inspect

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - dedop --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

# The app section is for creating entries in the Anaconda Launcher / Navigator
app:
  entry: open ${PREFIX}/Scripts/dedop-shell.bat      # [win]
  entry: open ${PREFIX}/bin/dedop-shell.command      # [osx]
  entry: open ${PREFIX}/bin/dedop-shell.sh           # [unix]
  icon: dedop.png
  own_environment: False
  summary:  "Delay Doppler Altimeter Tool"

about:
  home: https://github.com/DeDop/dedop
  license: MIT
  license_file: LICENSE
  summary: "DeDop is a User Configurable Tool for Processing Delay Doppler Altimeter Data."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
