version: '0.5.4.dev1'

build: off

branches:
  only:
    - master

skip_tags: true

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - conda install -y constructor anaconda-client
  - conda build -c ccitools recipe
  - DEDOP_OUTPUT=$(conda build -c ccitools recipe)
  - anaconda -v -t $ANACONDA_TOKEN upload "$DEDOP_OUTPUT" -u dedop --force
  - constructor installer

artifacts:
  - path: '*.exe'
    name: dedop-core-installer-exe