version: '0.5.4.dev1.{build}'

environment:
  global:
    # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
    ANACONDA_TOKEN:
      secure: "8Wuonn7zuZIDXX26rNMQ+ivY6msM56v7d0TNUpQ7rUy291IxaW88aWDEPYDthTZ8"

build: off

branches:
  only:
    - master

skip_tags: true

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - conda install -y conda-build constructor anaconda-client
  - conda build -c ccitools recipe
  - ps: $DEDOP_OUTPUT=conda build -c ccitools recipe --output
  - anaconda -v -t %ANACONDA_TOKEN% upload "%DEDOP_OUTPUT%" -u dedop --force
  - constructor installer

artifacts:
  - path: '*.exe'
    name: dedop-core-installer-exe