build: off

branches:
  only:
    - master

skip_tags: true

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - ps: ls "C:\Miniconda35-x64\NSIS\Contrib\Modern UI 2"
  - conda install -y constructor
  - ps: ls "C:\Miniconda35-x64\NSIS\Contrib\Modern UI 2"
  - constructor installer

artifacts:
  - path: '*.exe'
    name: dedop-core-installer-exe